# Attempt to find Dolfin

FIND_PATH( DOLFIN_INCLUDE_DIR dolfin.h "/usr/local/include" )

FIND_LIBRARY( DOLFIN_LIBRARY dolfin "/usr/local/lib" )

FIND_PATH( DOLFIN_LIBRARY_DIR dolfin "/usr/local/lib" )

IF( DOLFIN_INCLUDE_DIR AND DOLFIN_LIBRARY )  
  SET( DOLFIN_FOUND TRUE )
ENDIF( DOLFIN_INCLUDE_DIR AND DOLFIN_LIBRARY )

IF( DOLFIN_FOUND )
  IF( NOT DOLFIN_FIND_QUIETLY )
    MESSAGE( STATUS "Found DOLFIN: ${DOLFIN_LIBRARY}" )
  ENDIF(NOT DOLFIN_FIND_QUIETLY )
ELSE( DOLFIN_FOUND )
  IF( DOLFIN_FIND_REQUIRED )
    MESSAGE( FATAL_ERROR "Could not find DOLFIN!" )
  ENDIF( DOLFIN_FIND_REQUIRED )
ENDIF( DOLFIN_FOUND )
